swagger: "2.0"
info:
  description: "This is a kyc manage server"
  version: "1.0.0"
  title: "Blockshine kyc"
  termsOfService: "http://127.0.0.1"
  contact:
    email: "hhy5861@gmail.com"
host: "192.168.21.108:8090"
basePath: "/v1"
tags:
- name: "basicinfo"
  description: "basicinfo manage"
  externalDocs:
    description: "Basicinfo  Management"
    url: "http://swagger.io"

- name: "certificate"
  description: "certificate manage"
  externalDocs:
    description: "Certificate Management"
    url: "http://swagger.io"

schemes:
- "http"
paths:
  /basic-info/add:
    post:
      tags:
      - "basicinfo"
      summary: "Add a new basic info"
      description: "Add a new basic info"
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Add a new basic info"
        required: true
        schema:
          $ref: "#/definitions/AddBasicinfo"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BasicinfoResponse"

      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  /basic-info/search:
    get:
      tags:
      - "basicinfo"
      summary: "get basic info list"
      description: "get basic info list"
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "user_id" 
          in: "query"
          description: "user id"
          type: "integer"
        - name: "last_name" 
          in: "query"
          description: "last name"
          type: "string"
        - name: "first_name" 
          in: "query"
          description: "first name"
          type: "string"
        - name: "country_name" 
          in: "query"
          description: "country name"
          type: "string"
        - name: "sex" 
          in: "query"
          description: "sex"
          type: "integer"
        - name: "page" 
          in: "query"
          description: "get page number"
          type: "integer"
        - name: "size" 
          in: "query"
          description: "get page size number"
          type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BasicinfoResponse"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  /basic-info/basic-info-by-user-id:
    get:
      tags:
      - "basicinfo"
      summary: "get basic info by user id"
      description: "get basic info by user id"
      operationId: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "user_id" 
          in: "query"
          description: "user id"
          required: true
          type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BasicinfoResponse"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  #certificate start
  /certificate/info:
    get:
      tags:
      - "certificate"
      summary: "get certificate by user id"
      description: "get certificate by user id"
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "user_id" 
        in: "query"
        description: "user id"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CertificateResponseList"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  /certificate/search:
    get:
      tags:
      - "certificate"
      summary: "get certificate list"
      description: "get certificate list"
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "user_id" 
          in: "query"
          description: "user id"
          type: "integer"
        - name: "certificate_type" 
          in: "query"
          description: "certificate type"
          type: "integer"
        - name: "certificate_number" 
          in: "query"
          description: "certificate number"
          type: "string"
        - name: "page" 
          in: "query"
          description: "get page number"
          type: "integer"
        - name: "size" 
          in: "query"
          description: "get page size number"
          type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CertificateResponseList"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  /certificate/add:
    post:
      tags:
      - "certificate"
      summary: "Add a new basic info"
      description: "Add a new basic info"
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Add a new basic info"
        required: true
        schema:
          $ref: "#/definitions/AddCertificate"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CertificateResponseList"

      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"

  /certificate/review:
    put:
      tags:
      - "certificate"
      summary: "review certificate"
      description: "review certificate"
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "review certificate"
        required: true
        schema:
          $ref: "#/definitions/ReviewCertificate"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/CertificateResponseList"

      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"


definitions:
  #basicinfo
  AddBasicinfo:
    type: "object"
    required:
      - "user_id"
      - "last_name"
      - "first_name"
      - "birthday"
      - "country_name"
      - "sex"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      last_name:
        type: "string"
      first_name:
        type: "string"
      birthday:
        type: "string"
      country_name:
        type: "string"
      sex:
        type: "integer"
        format: "int64"
        description: "性别(0:女,1:男)"

  BasicinfoResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      data:
        $ref: "#/definitions/BasicinfoData"
  BasicinfoData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      last_name:
        type: "string"
      first_name:
        type: "integer"
        format: "int64"
      birthday:
        type: "string"
      country:
        type: "integer"
        format: "int64"
      country_name:
        type: "string"
      sex:
        type: "integer"
        format: "int64"
      check_status:
        type: "integer"
        format: "int64"
      message:
        type: "integer"
        format: "int64"
      valid:
        type: "integer"
        format: "int64"
      created_at:
        type: "string"
      updated_at:
        type: "string"

  #certificate

  AddCertificate:
    type: "object"
    required:
      - "user_id"
      - "certificate_type"
      - "certificate_number"
      - "validity_period"
      - "image_url"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      certificate_type:
        type: "integer"
        format: "int64"
      certificate_number:
        type: "string"
      validity_period:
        type: "string"
      image_url:
        type: "string"
  
  ReviewCertificate:
    type: "object"
    required:
      - "user_id"
      - "certificate_type"
      - "certificate_number"
      - "validity_period"
      - "image_url"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      certificate_type:
        type: "integer"
        format: "int64"
      certificate_number:
        type: "string"
      validity_period:
        type: "string"
      image_url:
        type: "string"
  
  CertificateResponseList:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      data:
        type: "array"
        items:
          $ref: "#/definitions/CertificateData"
  CertificateData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      certificate_type:
        type: "integer"
        format: "int64"
      certificate_number:
        type: "string"
      validity_period:
        type: "string"
      image_url:
        type: "string"
      check_status:
        type: "string"
      message:
        type: "string"
      valid:
        type: "integer"
        format: "int64"
      created_at:
        type: "string"
      updated_at:
        type: "string"

